config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :books do
    resources :favorites, only: [:create, :destroy]
    member do
      get 'review_modal', to: 'books#review_modal'

    end
  end

  resources :publishers do
    resources :authors
  end

  resources :authors do
    resources :books do 
    end
  

  end

  resources :authors do
    member do
      get 'about_modal' # Add this line to define the new action
    end
  end


  resources :authors

  root 'books#home'
  resources :price_updates, only: [:new, :create]

  namespace :api do
    resources :books do
      collection do
        get 'filter_title'
        get 'filter_author'
        get 'filter_price'
      end
    end
  end

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :nullify

  belongs_to :publisher, optional: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :date_of_birth, presence: true
  validates :about, presence: true

  def author_age
    if date_of_birth.present?
      age = Date.today.year - date_of_birth.year
      age -= 1 if Date.today < date_of_birth + age.years
      age
    end
  end

  def associated_books
    books.count
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.includes(:books).paginate(page: params[:page], per_page: 7)
    @search = params[:search]

    if @search.present?
      @authors =
        Author
        .where('authors.first_name ILIKE ? OR authors.last_name ILIKE ?', "%#{@search}%", "%#{@search}%")
        .paginate(page: params[:page], per_page: 10)
    end
  end

  def about_modal
    @author = Author.find(params[:id])
    render 'remote_modal', layout: true
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to books_path, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    author = Author.find(params[:id])
    if author.update(author_params)
      redirect_to books_path, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy
    redirect_to books_path, notice: 'Author was successfully deleted.'
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name, :date_of_birth, :about, :nationality, :publisher_id)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_search.html.erb
<%= form_tag(authors_path, method: :get) do %>
  <div class="search-publishers">
    <%= text_field_tag :search, params[:search],  placeholder: 'Search authors...' %>

  <%= submit_tag 'Search', style:" height: 2.3vw", class: 'search-publishers-btn'  %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<main class="edit-author-container">

<h3>Edit Author</h3>
<%= form_for @author do |f| %>
   <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
      <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
         <div class="field">
      <%= f.label :date_of_birth %>
   <%= f.date_field :date_of_birth %>
    </div>
         <div class="field">
      <%= f.label :about %>
      <%= f.text_area :about %>
    </div>
         <div class="field">
      <%= f.label :nationality %>
      <%= f.text_field  :nationality %>
    </div>
     

  <div class="edit-author-btn">
    <%= f.submit "Update Author", style: "height: 3.8vw ; width: 10vw ; font-size: 1vw", class: "edit-author" %>
     <%= f.submit "Update Author", style: "height: 6vw ; width: 18vw ; font-size: 2.1vw", class: "edit-author-mob" %>
  </div>
<% end %>
<div>
  <%= link_to "Back", authors_path %>
</div>
</main>

app/views/authors/index.html.erb
<main class="authors-list-container">
<%if @authors.empty? && @search.blank?%> 
<div class="no-authors">
    <p>There are no authors yet</p>
</div>
 <% elsif @authors.empty? %>
    <div>
      <p>No results found for: <%= params[:search] %></p>
    </div>
<%else%>
    <div class="search">

 <%= render partial:  "authors/search" %>
</div>


    <h1>Authors</h1>

<section class="authors-list">
<%  @authors.each do |author| %>
<div class="author-ind">
<h5><%=  author.first_name + " " +  author.last_name%></h5>
   <p>Associated books: <%= author.associated_books %></p>
 <%= link_to "See author", author_path(author)%>
</div>
<% end%>
<%end%>
</section>
<div class="authors-links"> 
<%= link_to "Add new author", new_author_path ,style:"font-size : 3vw; width: 10vw"  ,class:"add-btn-mob " %>
 <%= link_to "Home", books_path,style:"font-size : 3vw; width: 10vw" , class:" home-author-mob " %>
 <%= link_to "Add new author", new_author_path  ,class:"add-btn-desk " %>
 <%= link_to "Home", books_path, class:" home-author-desk " %>
</div>
<div class="pagination-logged">
<%= will_paginate @books %>
</div>

 <main>

app/views/authors/new.html.erb
<main class="authors-container">



<% if @author.present? %>
  <%= form_for [@author] do |f| %>
    <% if @author.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

        <ul>
        <% @author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<h1>Add Author</h1>
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name , required: true %>
    </div>
      <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name , required: true %>
    </div>
         <div class="field-date">
      <%= f.label :date_of_birth %>
   <%= f.date_field :date_of_birth , required: true %>
    </div>
         <div class="field">
      <%= f.label :about %>
      <%= f.text_area :about , required: true %>
    </div>
         <div class="field-about">
      <%= f.label :nationality %>
      <%= f.text_field  :nationality , required: true %>
    </div>
     
    
<div class="field-btn">
    <%= f.submit "Add Author",style: "height: 3.8vw" , class: "add-author" %>
        <%= f.submit "Add Author",style: "height: 8vw;font-size: 2.5vw" , class: "add-author-mob" %>
    </div>
    <div>
  <%= link_to "Go Back", books_path, class:"link-back" %>
</div>
  <% end %>
<% else %>
  <p> error</p>
<% end %>


</main>

app/views/authors/remote_modal.html.erb
<main class="author-about-container">
   <h1>
   <%= @author.first_name + " " + @author.last_name%>

   </h1>
    <div class="author-detaabout">
       <p>
         <%= @author.about %>
         </p>


</main>
<div class="addpub-back-link">
<%= link_to 'Back', author_path(@author.id) %>
</div>

app/views/authors/show.html.erb
<main class="author-detail-cont">

<div class="show-author-detail">
  <h5>Author:</h5>
<p><%= @author.first_name + " " + @author.last_name   %></p> 
</div>


<div class="show-author-detail" >
<h5>
Date of Birth:
</h5>
<p>
<%= @author.date_of_birth %>
</div>
<div class="show-author-detail">
<h5>
About this author:
</h5>
<p>
  <%= @author.about.to_s.split.take(6).join(" ") %>
  <%= link_to "see more", about_modal_author_path(@author.id) %>

</p>
</div>
<div class="show-author-detail">
<h5>
Country of origin:
</h5>
<p>
<%= @author.nationality %>
</p>
</div>




<div class="author-show-links">
<%= link_to  "Add book for this author", new_author_book_path(@author)%>
<%= link_to  "Update author", edit_author_path(@author.id)%>
<%= button_to "Delete author ",  @author, method: :delete, class:"delete-author-btn" %>


  <%= link_to "Back", authors_path %>
</div>