config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :books do
    resources :favorites, only: [:create, :destroy]
    member do
      get 'review_modal', to: 'books#review_modal'

    end
  end

  resources :publishers do
    resources :authors
  end

  resources :authors do
    resources :books do 
    end
  

  end

  resources :authors do
    member do
      get 'about_modal' # Add this line to define the new action
    end
  end


  resources :authors

  root 'books#home'
  resources :price_updates, only: [:new, :create]

  namespace :api do
    resources :books do
      collection do
        get 'filter_title'
        get 'filter_author'
        get 'filter_price'
      end
    end
  end

end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :nullify

  has_many :authors, through: :books, dependent: :nullify
  validates :name, presence: true
  validates :name, uniqueness: true

  def associated_books
    number_of_books = books.count
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.paginate(page: params[:page], per_page: 4)
    @search = params[:search]

    if @search.present?
      @publishers =
        Publisher
        .where('publishers.name ILIKE ?', "%#{@search}%")
        .paginate(page: params[:page], per_page: 10)
    end
    if @publishers.empty?
      # No results found for the search
      flash.now[:notice] = "No publishers match your search."
    end
  end

  def show
    @publisher = Publisher.find(params[:id])
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      redirect_to publishers_path
    else
      render :new
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])

    if @publisher.update(publisher_params)
      redirect_to books_path, notice: 'Publisher was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    redirect_to books_path, notice: 'Publisher was successfully deleted.'
  end

  private

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_search.html.erb
<%= form_tag(publishers_path, method: :get) do %>
  <div class="search-publishers">
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search Publishers...' %>
  <%= submit_tag 'Search', style:" height: 2.3vw", class: 'search-publishers-btn' %>
  </div>

<% end %>

app/views/publishers/edit.html.erb
<main class="add-publisher-container" >
<%= form_for @publisher do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Update Publisher",style:"height: 3vw; width:10vw; font-size: 1vw" ,class:"add-pub-btn" %>
     <%= f.submit "Update Publisher",style:"height: 7vw; width:16vw; font-size: 2vw" ,class:"add-pub-btn-mob" %>
  </div>
<% end %>
</main>
<div class="addpub-back-link">
  <%= link_to "Back", books_path %>
</div>
  

app/views/publishers/index.html.erb
<main class="publishers-container">
  <h1 class="publishers-title">Publishers</h1>
  <% if @publishers.empty? && @search.blank? %>
    <h2 class="no-publishers">There are no publishers yet</h2>
    <%= link_to "Add a Publisher", new_publisher_path, class: "no-publisher-link" %>
  <% elsif @publishers.empty? %>
    <div>
      <p>No results found for: <%= params[:search] %></p>
    </div>
  <% else %>
    <div class="search">
      <%= render partial: "publishers/search" %>
    </div>
    <section class="publishers-list">
      <% @publishers.each do |publisher| %>
    
    <div class="publisher">
    <section class="publisher-up">
      <h2>Publisher's name:</h2>
      <h2><%= publisher.name %></h2>
        <p>Associated books: <%= publisher.associated_books %></p>
        </section>
        <section class="publisher-down">
          <%= link_to "update publisher" , edit_publisher_path(publisher.id),class:"pub-links" %>
        <%= button_to "Delete publisher ", publisher, method: :delete ,class:"pub-links btn-pub"%>
        </section>
        </div>
        
    
        
    
    
 

      <% end %>
    </section>
  <% end %>














<div class="pagination-logged">
<%= will_paginate @books %>
</div>

  </main>
  <div class="addpub-back-link">
  <%= link_to "Back", books_path %>
</div>
  

app/views/publishers/new.html.erb
<main class="add-publisher-container">
<h2>Add Publisher</h2>
<%= form_for [@publisher] do |f| %>
    <% if @publisher.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

        <ul>
        <% @publisher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name , required: true %>
    </div>

    <%= f.submit "Add Publisher", style:"height: 3vw; width:10vw" ,class:"add-pub-btn" %>
  <% end %>
</main>
<div class="addpub-back-link">
  <%= link_to "Back", books_path %>
</div>
  
    
 

    

app/views/publishers/show.html.erb
<h2><%= @publisher.name%></h2>
<%= link_to "Home" , root_path%>