config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :books do
    resources :favorites, only: [:create, :destroy]
    member do
      get 'review_modal', to: 'books#review_modal'

    end
  end

  resources :publishers do
    resources :authors
  end

  resources :authors do
    resources :books do 
    end
  

  end

  resources :authors do
    member do
      get 'about_modal' # Add this line to define the new action
    end
  end


  resources :authors

  root 'books#home'
  resources :price_updates, only: [:new, :create]

  namespace :api do
    resources :books do
      collection do
        get 'filter_title'
        get 'filter_author'
        get 'filter_price'
      end
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :cover
  belongs_to :author
  has_many :favorites, dependent: :destroy
  belongs_to :publisher, optional: true
  validates :title, presence: true
  validates :isbn, presence: true, uniqueness: true
  validates :review, presence: true
  validates :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :date_of_publication, presence: true
  validates :title, length: { maximum: 255 }
  validates :review, length: { maximum: 1000 }
  validate :date_of_publication_not_in_future

  def date_of_publication_not_in_future
    if date_of_publication.present? && date_of_publication > Date.today
      errors.add(:date_of_publication, "can't be in the future")
    end
  end
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy, :filter]
  def index
    @books = Book.paginate(page: params[:page], per_page: params[:per_page] || 10)
    render json: @books, meta: pagination(@books)
  end

  def pagination(collection)
    {
      current_page: collection.current_page,
      per_page: collection.per_page,
      total_pages: collection.total_pages,
      total_entries: collection.total_entries
    }
  end

  def show
    @book = Book.find_by_id(params[:id])
    render json: @book
  end

  def create
    @book = Book.create(book_params)
    render json: @book
  end

  def update
    @book = Book.find_by_id(params[:id])
    @book.update(book_params)
    render json: @book
  end

  def destroy
    @book = Book.find_by_id(params[:id])
    @book.destroy
    render json: { message: 'Book Deleted' }
  end

  def filter_title
    # Apply filtering
    filtered_books = Book.all

    if params[:title].present?
      filtered_books = filtered_books.where("title ILIKE ?", "%#{params[:title]}%")
    end

    if filtered_books.empty?
      render json: { message: 'No books match the filter criteria' }, status: :not_found
      return
    end

    filtered_books = filtered_books.paginate(page: params[:page], per_page: params[:per_page])

    render json: filtered_books
  end

  def filter_author
    filtered_books = Book.all

    if params[:author].present?
      filtered_books = filtered_books.where("author_name ILIKE ?", "%#{params[:author]}%")
    end

    if filtered_books.empty?
      render json: { message: 'No books match the filter criteria' }, status: :not_found
      return
    end

    filtered_books = filtered_books.paginate(page: params[:page], per_page: params[:per_page])

    render json: filtered_books
  end

  def filter_price
    filtered_books = Book.all

    if params[:min_price].present? && params[:max_price].present?
      filtered_books = filtered_books.where("price >= ? AND price <= ?", params[:min_price], params[:max_price])
    end

    if filtered_books.empty?
      render json: { message: 'No books match the filter criteria' }, status: :not_found
      return
    end

    filtered_books = filtered_books.paginate(page: params[:page], per_page: params[:per_page])
    render json: filtered_books
  end

  private

  def book_params
    params.require(:book).permit(:title, :author_name, :author_id, :review, :price, :date_of_publication, :isbn,
                                 :publisher_id, :new_publisher_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource except: [:home, :index, :show]

  def home
    @books = Book.paginate(page: params[:page], per_page: 5)
  end

  def index
    @user = current_user
    @search = params[:search]
    @search_by = params[:search_by]
    @books = Book.paginate(page: params[:page], per_page: 5)

    if @search.present?
      case @search_by
      when 'Title'
        @books = @books.where('title ILIKE ?', "%#{@search}%")
      when 'ISBN'
        @books = @books.where('CAST(isbn AS text) LIKE ?', "%#{@search}%")
      when 'Author'
        @books = @books.joins(:author).where('authors.first_name ILIKE ? OR authors.last_name ILIKE ?', "%#{@search}%",
                                             "%#{@search}%")
      when 'Publisher'
        @books = @books.joins(:publisher).where('publishers.name ILIKE ?', "%#{@search}%")
      end
    end
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
    @user = current_user
  end



  def review_modal
    @book = Book.find(params[:id])
    render 'book_detail', layout: true
  end

  def new
    @author = Author.find(params[:author_id])
    @full_name = "#{@author.first_name} #{@author.last_name}"
    @book = @author.books.build
    @publishers = Publisher.all
  end

  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.build(book_params)

    if params[:book][:new_publisher_name].present?
      @book.publisher = Publisher.create(name: params[:book][:new_publisher_name])
    end

    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      # Book updated successfully
      redirect_to books_path, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    # Book deleted successfully
    redirect_to books_url, notice: 'Book was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author_name, :author_id, :review, :price, :date_of_publication, :isbn, :cover,
                                 :publisher_id, :new_publisher_name)
  end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% @books.each do |book|%>
<div class="book-home-logged  user-logged" >
<div class="book-title-logged">
    <h3>Title: </h3>
    <p><%= book.title %></p>
    </div>
    <div class="book-author-logged">
    <h3> Author: </h3>
    <p><%= book.author_name %></p>
    </div>
         <%=  link_to  "See Book" , book_path(book.id)  , class:"see-book-desk"%>
     <%=  link_to  "See Book" , book_path(book.id)  , style:"font-size: 2.5vw;line-height: 2.8vw  ", class:"see-book-mob"%>
    </div>

<%end%>

app/views/books/_book_home.html.erb
<% @books.each do |book|%>
<div class="book-home" >
<div class="book-title">
    <h3>Title: </h3>
    <p><%= book.title %></p>
    </div>
    <div class="book-author">
    <h3> Author: </h3>
    <p><%= book.author_name %></p>
    </div>
     <%=  link_to  "See Book" , book_path(book.id)%>
    </div>
<%end%>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_search.html.erb
<main class="search-books-container">
<%= form_tag(books_path, method: :get) do %>
<section class="search-books-form">
  <div class="">
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search books by...' %>
  </div>
  <div class="">
    <%= select_tag :search_by, options_for_select(['Title', 'ISBN', 'Author', 'Publisher'], params[:search_by]), class: 'search-select' %>
  </div>
  <div>
  
  <%= submit_tag 'Search',style:"height: 2.9vw ; width: 10vw",class: 'search-btn' %>
    <%= submit_tag 'Search',style:"height: 11.6vw ; width: 20vw; font-size: 3vw",class: 'search-btn-mobile' %>

  </div>
</section>
<% end %>

</main>

app/views/books/book_detail.html.erb
<main class="author-about-container">
   <h1>
   <%= @book.title%>

   </h1>
    <div class="author-detaabout">
       <p>
         <%= @book.review %>
         </p>


</main>
<div class="addpub-back-link">
<%= link_to 'Back', book_path(@book.id) %>
</div>

app/views/books/edit.html.erb
<main class="edit-book-container">
<h1 class="edit-title">Edit book</h1>
<%= form_for @book do |f| %>
 <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
      <div class="field">
      <%= f.label :isbn %>
      <%= f.number_field :isbn %>
    </div>
         <div class="field">

      <%= f.label :author_name %>
   <%= f.text_field :author_name, value: @full_name, readonly: false %>
    </div>
         <div class="field">
      <%= f.label :review %>
      <%= f.text_area :review %>
    </div>
         <div class="field">
      <%= f.label :date_of_publication %>
      <%= f.date_field  :date_of_publication %>
    </div>
        <div class="field">
      <%= f.label :price %>
      <%= f.number_field  :price %>
    </div>
        </div class="field">
     <%= f.file_field :cover %>
     </div>

  <div class="actions">
    <%= f.submit "Update Book", style:"width: 10vw; height:3vw",class:"edit-btn" %>
      <%= f.submit "Update Book", style:"width: 18vw; height:7vw;font-size: 2.2vw",class:"edit-btn-mob" %>
  </div>
<% end %>

</main>

<div class="addpub-back-link">
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/home.html.erb
<main class="home-container">
<div class="flash-messages-home">
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
    
  </div>
    <% flash.clear %>
  </div>


<% end %>
</div>
<h1>Welcome to the BooksStore</h1>

<div class="books-home">
<%= render partial: '/books/book_home' %>

</div>
<div class="pagination-home">
<%= will_paginate @books %>
</div>
</main>

app/views/books/index.html.erb
<main class="main-container"> 
<section class="section-left">
<% if can?  :manage, @books, @authors   %>
<div class="admin-panel"
 <%= render partial: "admin/admin_panel" %>
</div>
 <%else%>
 <%if user_signed_in?%>
 <section class="browser">
 <p>Browse books</p>
 </section>
  <%end%>
 <%end%>
</section>




<section class="section-right">
<div class="flash-messages-logged">
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
</div>
<% if @user == "admin"%>
<h1 class="logged-title"> Welcome Admin! </h1>




<%else%>
<h1  class="logged-title"> Welcome to the Bookstore! </h1>

<%end%>


<div class="books-list ">

    <%= render partial:  '/books/book' %>
  

</div>
<div class="pagination-logged">
<%= will_paginate @books %>
</div>

</section>

</main>

app/views/books/new.html.erb
<main class="add-book-container">





    <section class="section-form-right">

<% if @author.present? %>
  <%= form_for [@author, @book] do |f| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title , required: true %>
    </div>
      <div class="field">
      <%= f.label :isbn %>
      <%= f.number_field :isbn , required: true %>
    </div>
         <div class="field">
      <%= f.label :author_name %>
   <%= f.text_field :author_name, value: @full_name, readonly: true %>
    </div>
         <div class="field">
      <%= f.label :review, style: "margin-bottom: 0.3vw" ,class:"review-label-mob" %>
      <%= f.text_area :review , required: true %>
    </div>
    </section>
    <section class="section-form-left">
         <div class="field">
      <%= f.label :date_of_publication %>
      <%= f.date_field  :date_of_publication , required: true%>
    </div>
        <div class="field">
      <%= f.label :price %>
      <%= f.number_field  :price  , step: :any, required: true%>
    </div class="field">
     <%= f.file_field :cover %>
     </div>

<div class="field">
  <%= f.label :publisher_id  , style: "margin-bottom: 0.2vw"%>
  <%= f.collection_select :publisher_id, @publishers, :id, :name, prompt: "Select or Create a Publisher" , style: "width: 10vw" %>
</div>
<p>publisher not listed?</p>

<%= link_to "Create a new publisher", new_publisher_path %>

    <%= f.submit "Create Book", style: "width: 14vw; height: 4.5vw" ,class:"add-book-btn"%>
      <%= f.submit "Create Book", style: "width: 20vw; height: 6vw;font-size: 2vw" ,class:"add-book-btn-mob"%>
  <% end %>
  </section>
<% else %>
  <p>aca esta el error</p>
<% end %>
<div class="add-book-link">

<%= link_to "Back", authors_path %>
</div>
</main>

app/views/books/search.html.erb
<% if @books.any? %>
  <h2>Search Results</h2>
  <ul>
    <% @books.each do |book| %>
      <li><%= link_to book.title, book %></li>
    <% end %>
  </ul>
<% else %>
  <p>No books found.</p>
<% end %>

app/views/books/show.html.erb
<main class="show-book-container">

<section  class="book-show">
<div class="detail detail-title ">
<h3>Title:</h3>
<p><%= @book.title %></p>
</div>
<div class="detail detail-author">
<h3> Author:</h3>
<p><%= @book.author_name %></p>
<h3>Age: </h3>
<p><%= @book.author.author_age %></p>

</div>
<div class="detail detail-isbn">
  <h3>ISBN: </h3>
  <p><%= @book.isbn %></p>
</div>
<div class="detail detail-date">
  <h3>Date of publication: </h3>
  <p><%= @book.date_of_publication %></p>
</div>
<div class="detail detail-publisher">
  <h3>Publisher: </h3>
  <p><%= @book.publisher.name %></p>
</div>
<div class="detail detail-review">
   <h3>Review:</h3>
  <p><%= @book.review.to_s.split.take(6).join(" ") %>
  <%= link_to "...see more",  review_modal_book_path(@book.id) %></p>
</div>
<div class="detail detail-price">
     <h3>Price: </h3>
      <p>$ <%= @book.price %></p>
</div>






<div class="detail detail-links">
<% if can?  :manage, @books, @authors   %>
  <%= link_to "Edit this book", edit_book_path(@book) %>
  <%= button_to "Delete book", @book, method: :delete ,class: "delete-btn" %>

<%end%>
<% if user_signed_in?%>
  <%= link_to "Back to books", books_path %>
  <% else%>
  <%= link_to "Back to books", root_path %>
  <%end%>

</div>
</section>
<section class="book-cover">
<div class="cover">
<% if @book.cover.attached? %>
  <%= cl_image_tag @book.cover.key, :width=>290  ,:height=>480, :crop=>"fill" %>
<% else %>
  <p>No image available</p>
<% end %>

</div>
</section>

</main>