config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :books do
    resources :favorites, only: [:create, :destroy]
    member do
      get 'review_modal', to: 'books#review_modal'

    end
  end

  resources :publishers do
    resources :authors
  end

  resources :authors do
    resources :books do 
    end
  

  end

  resources :authors do
    member do
      get 'about_modal' # Add this line to define the new action
    end
  end


  resources :authors

  root 'books#home'
  resources :price_updates, only: [:new, :create]

  namespace :api do
    resources :books do
      collection do
        get 'filter_title'
        get 'filter_author'
        get 'filter_price'
      end
    end
  end

end

app/models/price_update.rb
class PriceUpdate < ApplicationRecord
  belongs_to :publisher, dependent: :destroy
end

app/controllers/price_updates_controller.rb
class PriceUpdatesController < ApplicationController
  def new
    @price_update = PriceUpdate.new
  end

  def create
    @price_update = PriceUpdate.new(price_update_params)
    if @price_update.save
      # Enqueue the Sidekiq job to update book prices
      PriceUpdateJob.perform_later(@price_update)
      flash[:success] = 'Price update job has been enqueued.'
      redirect_to root_path
    else
      render :new
    end
  end

  # ...

  private

  def price_update_params
    params.require(:price_update).permit(:publisher_id, :update_type, :percentage)
  end
end

app/helpers/price_updates_helper.rb
module PriceUpdatesHelper
end

app/views/price_updates/new.html.erb
<main class="update-price-cont">
<%= form_for @price_update, url: price_updates_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :publisher_id, 'Select Publisher' %>
    <%= f.collection_select :publisher_id, Publisher.all, :id, :name, prompt: 'Select a Publisher' %>
  </div>
  
  <div class="field">
    <%= f.label :update_type, 'Update Type' %>
    <%= f.select :update_type, [['Increase', 'increase'], ['Decrease', 'decrease']], prompt: 'Select Update Type' %>
  </div>

  <div class="field">
    <%= f.label :percentage, 'Percentage' %>
    <%= f.number_field :percentage, step: 0.01 , required: true %>
  </div>

  <%= f.submit 'Update Prices', style:"width: 8vw; height: 3.5vw; font-size: 1vw", class: 'update-btn' %>
  <%= f.submit 'Update Prices', style:"width: 16vw; height: 7vw; font-size: 2vw", class: 'update-btn-mob' %>
<% end %>

<div class="addpub-back-link">
<%= link_to 'Back', books_path %>
</div>
</main>